services:
  postgres:
    image: postgres:17.4-alpine
    # inject credentials from .env
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    env_file:
      - .env
    command: >
      sh -c "if [ -n \"$REDIS_PASSWORD\" ]; then
               exec redis-server --requirepass \"$REDIS_PASSWORD\";
             else
               exec redis-server;
             fi"
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    # pick up any backend-specific env plus the DB/Redis creds
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "${BACKEND_PORT}:3001"

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:3000"

volumes:
  pgdata: